sequenceDiagram
    participant atom
    participant view
    participant elm
    atom->>view: SEND positionChanged
    view-->>elm: REQUEST register position
    Note over elm: REGISTER position
    Note over atom,elm: ...zzz...
    atom->>view: SEND back command
    view-->>elm: REQUEST back
    Note over elm: is_jumping = TRUE
    elm->>view: SEND backJumped
    view->>atom: SEND position
    atom->>view: SEND positionChanged
    view-->>elm: REQUEST register position
    Note over elm: NOP since is_jumping = TRUE
    atom->>view: SEND back command
    view-->>elm: REQUEST back
    Note over elm: NOP since is_jumping = TRUE
    Note over atom,elm: ...zzz...10ms? .....zzz...
    Note over elm: is_jumping = FALSE
    atom->>view: SEND positionChanged
    view-->>elm: REQUEST register position
    Note over elm: REGISTER position
